language: erlang
before_install:
  - sudo apt-get install protobuf-compiler libprotoc-dev libprotobuf-dev
install:
  - "echo 'Nothing to install; skipping ...'"
script:
  - "make check-travis"
notifications:
  irc: "irc.freenode.org#bolya"
  recipients:
    - eng@billo.systems
otp_release:
  - 19.2
  - 18.3
  - 17.5
  - R16B03
  - R15B03

