language: erlang
before_install:
  - sudo apt-get install protobuf-compiler libprotoc-dev libprotobuf-dev
install:
  - "echo 'Nothing to install; skipping ...'"
before_script:
  - "make get-lfetool"
script:
  - "make check-travis"
notifications:
  irc: "irc.freenode.org#bolya"
  recipients:
    - eng@billo.systems
otp_release:
  - 17.1
  - R16B03
  - R15B03

